[package]
name = "dcs-contrib-sequent-rtd"
version = "0.1.0"
authors = ["kolektiv <andrew@xyncro.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
